[package]
name = "chaosgame"
version = "0.1.0"
authors = ["János Illés <ijanos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.3"
rand = "0.7.3"